### ISSUE TITLE
Asignación de tareas

### ISSUE THREAD

**Issue by m5991** [m5991/tecnologiaMexico#1]
En el proyecto inicialmente, cada quien hará una parte del análisis.

- [x] Scikit-Learn @rgutierrezroque 
- [x] Altair @m5991 
- [x] Mapas @D4NT3002 
- [x]  Redactar un doc de resultados
- [x]  Terminar README principal
- [x]  Poner referencias utilizadas

**Comment by rgutierrezroque** [comment]
El notebook con la primer versión de árboles de decisión ya esta cargada para que la puedan revisar.

**Comment by D4NT3002** [comment]
Tenemos mapas y EDA
